version: '3'

services:
  app:
    container_name: analyze-stocks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
